# Generated by Django 2.0 on 2018-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
