# Generated by Django 2.0 on 2018-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='initial_price',
            field=models.PositiveSmallIntegerField(blank=True, editable=False),
        ),
    ]
