# Generated by Django 2.0 on 2018-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20180219_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='initial_price',
            new_name='initial_amount',
        ),
    ]
