# Generated by Django 2.0 on 2018-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20180219_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='rooms',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
