# Generated by Django 2.0 on 2018-02-19 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_checkin_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date_time', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='check_in_date_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='last_edited_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='check_in',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.CheckIn'),
        ),
    ]
