# Generated by Django 2.0 on 2018-02-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20180219_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='stay_duration',
            field=models.DurationField(editable=False, null=True),
        ),
    ]
