# Generated by Django 2.0 on 2018-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20180220_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pay_amount',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_amount',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
