# Generated by Django 2.0 on 2018-01-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_customer', to='main.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('SM', 'Simple'), ('DX', 'Deluxe'), ('PM', 'Premium')], default='SM', max_length=2)),
                ('availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_customer', to='main.Reservations')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservations')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_staff', to='main.Reservations')),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_staff', to='main.Staffs'),
        ),
    ]
