# Generated by Django 2.0 on 2018-01-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('SM', 'Simple'), ('DX', 'Deluxe'), ('PM', 'Premium')], default='SM', max_length=2)),
                ('availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_customer', to='main.Reservation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservation')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_staff', to='main.Reservation')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='staff',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Staffs',
            new_name='Staff',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_customer', to='main.Customer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_staff', to='main.Staff'),
        ),
    ]
