# Generated by Django 2.0 on 2018-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180209_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profilepic',
            field=models.ImageField(default='static/images/staff.png', upload_to='static/staff_img/'),
        ),
    ]
