# Generated by Django 2.0 on 2018-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180109_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='no_of_children',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
