# Generated by Django 2.0 on 2018-01-09 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reservation_no_of_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 10, 56, 9, 715260)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 10, 56, 9, 715279)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_of_adults',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 10, 56, 9, 715229)),
        ),
    ]
