# Generated by Django 2.0 on 2018-02-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180211_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(default='staff.png', upload_to='static/staff_img/'),
        ),
    ]
