# Generated by Django 2.0 on 2018-02-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180211_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(default='staffs.png', upload_to='static/staff_img/'),
        ),
    ]
