# Generated by Django 2.0 on 2018-02-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180211_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(default='images/staff.png', upload_to='staff_img/'),
        ),
    ]
