# Generated by Django 2.0 on 2018-03-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180211_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Reservation'),
        ),
    ]
