# Generated by Django 2.0 on 2018-01-09 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_customer', to='main.Customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 11, 37, 9, 84934)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 11, 37, 9, 84952)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 11, 37, 9, 84903)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_staff', to='main.Staff'),
        ),
        migrations.AlterField(
            model_name='room',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_customer', to='main.Reservation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Reservation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_staff', to='main.Reservation'),
        ),
    ]
