# Generated by Django 2.0 on 2018-01-09 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180109_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 10, 54, 34, 887458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 10, 54, 34, 887500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 10, 54, 34, 887395, tzinfo=utc)),
        ),
    ]
