# Generated by Django 2.0 on 2018-01-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180109_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_no']},
        ),
        migrations.AlterField(
            model_name='staff',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
