# Generated by Django 2.0 on 2018-01-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180109_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
