# Generated by Django 2.0 on 2018-01-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_sidebaritems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SidebarItems',
            new_name='SidebarItem',
        ),
    ]
