# Generated by Django 2.0 on 2018-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180111_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SidebarItem',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
