# Generated by Django 2.0 on 2018-01-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180112_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
