# Generated by Django 2.0 on 2018-01-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180112_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
