# Generated by Django 2.0 on 2018-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180112_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
