# Generated by Django 2.0 on 2018-01-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180113_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Facility',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='service',
            new_name='facility',
        ),
    ]
