# Generated by Django 2.0 on 2018-01-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20180123_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff'),
        ),
    ]
